### ISSUE TITLE
UglifyJs Invalid assignment

### ISSUE THREAD

**Issue by knynkwl** [mjbp/storm-scroll-spy#1]
I am getting this error when using Uglify with Webpack.

This is where it's producing the error.
```const init = (sel, opts) => {```

**Comment by mjbp** [comment]
That looks like it's down Uglify's lack of ES6 support. The newest uglifyjs-webpack-plugin (https://webpack.js.org/plugins/uglifyjs-webpack-plugin/) that uses uglify-es under the hood should avoid that.

This thread - https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/187 - has a description of the issue and [this post](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/187#issuecomment-349814895) shows a full solution that may be useful.
